spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/desapega
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        use_sql_comments: true
